#title: Ousseni M.
logo: /assets/image.jpeg
show_downloads: true
theme: jekyll-theme-minimal

name: Ousseni Mbohou
title: Junior Software Developer
email: oussenimbohou@gmail.com
description: Junior Software Developer | Portfolio
